import logging
from typing import Dict, Any
from app.models.simulation import SeanceReport

logger = logging.getLogger("phantom.case_studies")

class GhostStoryGenerator:
    """
    Forensic Case Study Generator.
    Converts raw Séance Reports into high-authority Narration.
    """
    
    def generate_story(self, report: SeanceReport) -> str:
        """
        Generates a Markdown-formatted 'Ghost Story'.
        """
        title = f"The Forensic Séance of {report.target_url.host}"
        
        # Determine the narrative tone based on HFS
        if report.confusion_score > 40:
            tone = "Critical Failure"
            conclusion = "The interface actively resisted user intent, leading to a total collapse of the conversion funnel."
        else:
            tone = "Friction Optimization"
            conclusion = "Subtle behavioral friction points are draining potential LTV. Optimization is required to reach PMF velocity."

        story = f"""# {title}
        
## Status: {tone}
**HFS (Human Friction Score):** {report.confusion_score}
**Ghosts Deployed:** {report.ghosts_deployed}

### 🏺 Forensic Findings

"""
        for point in report.friction_points:
            story += f"- **{point.element}**: {point.issue} (Impact: {point.impact * 100}%)\n"
            
        story += f"\n### 🧪 The Solution\n{conclusion}\n\n"
        story += "---\n*Generated by the Phantom Ghost Story Protocol v0.1.0*"
        
        return story

case_story_generator = GhostStoryGenerator()
